### PR TITLE
refactor(): Store v2 compatibility

### PR DESCRIPTION
**Pull request by MikeRyan52**

### CODE REVIEW

**Comment by oskarols** [comment]
Anything in particular needed to get this out the door?

I tried using this branch directly, and the app was failing to load due to the `INIT_ACTION` in reducer.ts not being set to a value.

**Comment by MikeRyan52** [comment]
@oskarols I was trying to defer release until I had support for the redux devtools Chrome extension in place, but that's going slower than anticipated. I may release a beta in the meantime.

**Comment by NathanWalker** [comment]
@MikeRyan52 Would be great to see this go on; will allow me to update this to 2.0 as well:
https://github.com/vakrilov/ngrx-devtools-nativescript

**Comment by bzums** [comment]
Anything particular holding this back?

**Comment by MikeRyan52** [comment]
The plan is to split the repository into two parts:

**@ngrx/store-devtools**
This will include all of the instrumentation code and remove the dependency on Angular 2. This should make it easier to use the instrumentation in projects where you don't want to bring in Angular 2 as a dependency. Additionally, it will eventually have support for [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension). There is mostly broken support for it already, I'll (hopefully) be working more with @zalmoxisus over the coming weeks to get this feature ready.

**@ngrx/store-log-monitor**
This is the Angular 2 Devtools component that shipped with v1.x of this project. It will have some enhancements, but assuming we can lock down support for redux-devtools-extension I don't think it needs to be included as part of base setup. It will still be maintained and should be a good reference for creating monitors using the devtools services.

I will get the repositories setup, and assuming the proposed plan moves forward I'll release a beta 1 or something.

cc @NathanWalker @Hotell @zalmoxisus @robwormald @brandonroberts

**Comment by MikeRyan52** [comment]
An example of configuring instrumentation under this proposed plan can be found in the [readme of my refactor branch](https://github.com/mikeryan52/devtools/tree/v2)

**Comment by MikeRyan52** [comment]
Released. See the demo here: http://ngrx.github.io/example-app/

**Pull request merged**
